# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      #      - name: Build JsonConfiguration
      #        run: |
      #          git clone https://github.com/sandtechnology/JsonConfiguration.git
      #          mvn -B install --file JsonConfiguration/pom.xml
      #      - name: Build Integration
      #        run: mvn -B install --file src/integration/plotsquared/5/pom.xml
      - name: Build with Maven
        run: mvn -B test --file pom.xml -Pdebug
      - name: upload jar
        uses: actions/upload-artifact@v3
        with:
          name: QuickShop
          path: |
            **/target/*.jar
